[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
range-ext = "0.3.0"
trie-rs = "0.1.1"
winnow = "0.5.19"
